apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: elastic-logging
  labels:
    app: kibana
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: eks.amazonaws.com/nodegroup
                operator: In
                values:
                - private-nodes-eks
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:latest
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 100m
        env:
         - name: ELASTICSEARCH_HOSTS
           value: http://elasticsearch:9200
        envFrom:
        - secretRef:
            name: kibana-creds
        ports:
        - containerPort: 5601
---
apiVersion: v1
data:
  ELASTICSEARCH_USERNAME: ZWxhc3RpYw== #elastic 
  ELASTICSEARCH_PASSWORD: Y2hhbmdlbWU= #changeme
kind: Secret
metadata:
  name: kibana-creds
  namespace: elastic-logging
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: elastic-logging
  labels:
    app: kibana
spec:
  ports:
  - port: 5601
  selector:
    app: kibana